### ISSUE TITLE
Monorepo: Hardhat + Frontend

### ISSUE THREAD

**Issue by codesport** [sashadev-sky/Rock-Paper-Scissors-Mint#1]
@sashadev-sky

You did a great job with your documentation for setting up the mono-repo. Excellent Documentation! 

Any luck getting the monorepo  to work with Hardhat 2.10.x?

Last week I spend too much time building a bash script to automate the set-up and install for the mono-repo with Hardhat, Next, and Tailwind. 

Was able to get hardhat 2.10.x to auto install everything. **BUT**, it would not do it inside  a workspace sub-folder. Neither manually nor with the script.

Will post script for you if I can get it working. Thanks again for your tutorial.

**Comment by sashadev-sky** [comment]
There aren't any updates with this version pertaining to my setup. Are you referring to the `hardhat` command to init a new Hardhat project from my wikis? You need to make sure there is no `hardhat.config.js` in the folder and that hardhat is a dependency in that subfolder

**Comment by codesport** [comment]
Just manually did your commands from the wiki and yarn would not let hardhat install inside a workspace.  It only would install in the parent folder.

started with an empty parent folder.  wanted to bootstrap projects quickly with yarn berry, hardhat , typescript, and next.js.

You did an excellent job in documenting how to get TypeScript to play nice after installing Hardhat.

Thanks so much for the excellent and thorough tutorial

**Comment by codesport** [comment]
Sasha,

I'll close out this issue. Thanks again for the feedback.

Although at times I was able to get them to work together intermittently, I've confirmed that yarn berry and hardhat are not compatible.  

https://github.com/NomicFoundation/hardhat/issues/586#issuecomment-1140543657
